trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
      checkLatest: true

  - script: |
      cd client
      npm install
      npm run build
    displayName: "Install and Build React App"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "client/dist"
      Contents: "**"
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "reactapp"
