// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNet.Migrations
{
    [DbContext(typeof(SamplePoolDBContext))]
    partial class SamplePoolDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNet.Models.Pool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HostFK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HostFK");

                    b.ToTable("Pools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Join this test league to see other features within the environment. As Survivor Season 1 aired in 2000, this current league is closed for actual participants. This pool shows a type where participants gain points as their contestant stays in the competition. The other type of pool allows players to guess when contestants get eliminated similar to NCAA brackets.",
                            HostFK = "abutler",
                            Name = "Lone Survivors",
                            SourceLink = "https://en.wikipedia.org/wiki/Survivor:_Borneo",
                            SourceName = "Survivor Season 1"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Here is another test league to see how data can transition within the application. Survivor Season 2 allows us to see how to use the same host name and participants within a new pool.",
                            HostFK = "abutler",
                            Name = "Lone Survivors Revival",
                            SourceLink = "https://en.wikipedia.org/wiki/Survivor:_The_Australian_Outback",
                            SourceName = "Survivor Season 2"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "We have another Survivor league! Our fake participants hyped up the stakes and did their final season with our league.",
                            HostFK = "abutler",
                            Name = "Lone Survivors Final Boss",
                            SourceLink = "https://en.wikipedia.org/wiki/Survivor:_Africa",
                            SourceName = "Survivor Season 3"
                        });
                });

            modelBuilder.Entity("DotNet.Models.PoolMember", b =>
                {
                    b.Property<string>("UsernameFK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PoolNameFK")
                        .HasColumnType("int");

                    b.Property<string>("Contestant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.HasKey("UsernameFK", "PoolNameFK");

                    b.HasIndex("PoolNameFK");

                    b.ToTable("PoolMembers");

                    b.HasData(
                        new
                        {
                            UsernameFK = "rrosalind",
                            PoolNameFK = 1,
                            Contestant = "Richard",
                            Points = 15,
                            Rank = 1
                        },
                        new
                        {
                            UsernameFK = "jjeff",
                            PoolNameFK = 1,
                            Contestant = "Kelly",
                            Points = 14,
                            Rank = 2
                        },
                        new
                        {
                            UsernameFK = "abutler",
                            PoolNameFK = 1,
                            Contestant = "Rudy",
                            Points = 13,
                            Rank = 3
                        },
                        new
                        {
                            UsernameFK = "nnina",
                            PoolNameFK = 1,
                            Contestant = "Susan",
                            Points = 12,
                            Rank = 4
                        },
                        new
                        {
                            UsernameFK = "ppatrica",
                            PoolNameFK = 1,
                            Contestant = "Sean",
                            Points = 11,
                            Rank = 5
                        },
                        new
                        {
                            UsernameFK = "kkelley",
                            PoolNameFK = 1,
                            Contestant = "Coleen",
                            Points = 10,
                            Rank = 6
                        },
                        new
                        {
                            UsernameFK = "jjayden",
                            PoolNameFK = 1,
                            Contestant = "Gervase",
                            Points = 9,
                            Rank = 7
                        },
                        new
                        {
                            UsernameFK = "ttaylor",
                            PoolNameFK = 1,
                            Contestant = "Jenna",
                            Points = 8,
                            Rank = 8
                        },
                        new
                        {
                            UsernameFK = "pparis",
                            PoolNameFK = 1,
                            Contestant = "Greg",
                            Points = 7,
                            Rank = 9
                        },
                        new
                        {
                            UsernameFK = "kkathleen",
                            PoolNameFK = 1,
                            Contestant = "Gretchen",
                            Points = 6,
                            Rank = 10
                        },
                        new
                        {
                            UsernameFK = "aadam",
                            PoolNameFK = 1,
                            Contestant = "Joel",
                            Points = 5,
                            Rank = 11
                        },
                        new
                        {
                            UsernameFK = "sstephan",
                            PoolNameFK = 1,
                            Contestant = "Dirk",
                            Points = 4,
                            Rank = 12
                        },
                        new
                        {
                            UsernameFK = "ffrancis",
                            PoolNameFK = 1,
                            Contestant = "Ramona",
                            Points = 3,
                            Rank = 13
                        },
                        new
                        {
                            UsernameFK = "aapril",
                            PoolNameFK = 1,
                            Contestant = "Stacey",
                            Points = 2,
                            Rank = 14
                        },
                        new
                        {
                            UsernameFK = "llucy",
                            PoolNameFK = 1,
                            Contestant = "BB",
                            Points = 1,
                            Rank = 15
                        },
                        new
                        {
                            UsernameFK = "mmorgan",
                            PoolNameFK = 1,
                            Contestant = "Sonja",
                            Points = 0,
                            Rank = 16
                        },
                        new
                        {
                            UsernameFK = "ttaylor",
                            PoolNameFK = 2,
                            Contestant = "Tina",
                            Points = 15,
                            Rank = 1
                        },
                        new
                        {
                            UsernameFK = "aadam",
                            PoolNameFK = 2,
                            Contestant = "Colby",
                            Points = 14,
                            Rank = 2
                        },
                        new
                        {
                            UsernameFK = "mmorgan",
                            PoolNameFK = 2,
                            Contestant = "Keith",
                            Points = 13,
                            Rank = 3
                        },
                        new
                        {
                            UsernameFK = "nnina",
                            PoolNameFK = 2,
                            Contestant = "Elisabeth",
                            Points = 12,
                            Rank = 4
                        },
                        new
                        {
                            UsernameFK = "jjayden",
                            PoolNameFK = 2,
                            Contestant = "Rodger",
                            Points = 11,
                            Rank = 5
                        },
                        new
                        {
                            UsernameFK = "kkelley",
                            PoolNameFK = 2,
                            Contestant = "Amber",
                            Points = 10,
                            Rank = 6
                        },
                        new
                        {
                            UsernameFK = "kkathleen",
                            PoolNameFK = 2,
                            Contestant = "Nick",
                            Points = 9,
                            Rank = 7
                        },
                        new
                        {
                            UsernameFK = "pparis",
                            PoolNameFK = 2,
                            Contestant = "Jerri",
                            Points = 8,
                            Rank = 8
                        },
                        new
                        {
                            UsernameFK = "ffrancis",
                            PoolNameFK = 2,
                            Contestant = "Alicia",
                            Points = 7,
                            Rank = 9
                        },
                        new
                        {
                            UsernameFK = "aapril",
                            PoolNameFK = 2,
                            Contestant = "Jeff",
                            Points = 6,
                            Rank = 10
                        },
                        new
                        {
                            UsernameFK = "llucy",
                            PoolNameFK = 2,
                            Contestant = "Michael",
                            Points = 5,
                            Rank = 11
                        },
                        new
                        {
                            UsernameFK = "sstephan",
                            PoolNameFK = 2,
                            Contestant = "Kimmi",
                            Points = 4,
                            Rank = 12
                        },
                        new
                        {
                            UsernameFK = "abutler",
                            PoolNameFK = 2,
                            Contestant = "Mitchell",
                            Points = 3,
                            Rank = 13
                        },
                        new
                        {
                            UsernameFK = "ppatrica",
                            PoolNameFK = 2,
                            Contestant = "Maralyn",
                            Points = 2,
                            Rank = 14
                        },
                        new
                        {
                            UsernameFK = "rrosalind",
                            PoolNameFK = 2,
                            Contestant = "Kel",
                            Points = 1,
                            Rank = 15
                        },
                        new
                        {
                            UsernameFK = "jjeff",
                            PoolNameFK = 2,
                            Contestant = "Debb",
                            Points = 0,
                            Rank = 16
                        },
                        new
                        {
                            UsernameFK = "pparis",
                            PoolNameFK = 3,
                            Contestant = "Kim J",
                            Points = 15,
                            Rank = 1
                        },
                        new
                        {
                            UsernameFK = "mmorgan",
                            PoolNameFK = 3,
                            Contestant = "Ethan",
                            Points = 14,
                            Rank = 2
                        },
                        new
                        {
                            UsernameFK = "aapril",
                            PoolNameFK = 3,
                            Contestant = "Lex",
                            Points = 13,
                            Rank = 3
                        },
                        new
                        {
                            UsernameFK = "nnina",
                            PoolNameFK = 3,
                            Contestant = "Tom",
                            Points = 12,
                            Rank = 4
                        },
                        new
                        {
                            UsernameFK = "ttaylor",
                            PoolNameFK = 3,
                            Contestant = "Teresa",
                            Points = 11,
                            Rank = 5
                        },
                        new
                        {
                            UsernameFK = "jjeff",
                            PoolNameFK = 3,
                            Contestant = "Kim P",
                            Points = 10,
                            Rank = 6
                        },
                        new
                        {
                            UsernameFK = "kkathleen",
                            PoolNameFK = 3,
                            Contestant = "Frank",
                            Points = 9,
                            Rank = 7
                        },
                        new
                        {
                            UsernameFK = "ppatrica",
                            PoolNameFK = 3,
                            Contestant = "Brandon",
                            Points = 8,
                            Rank = 8
                        },
                        new
                        {
                            UsernameFK = "kkelley",
                            PoolNameFK = 3,
                            Contestant = "Kelly",
                            Points = 7,
                            Rank = 9
                        },
                        new
                        {
                            UsernameFK = "abutler",
                            PoolNameFK = 3,
                            Contestant = "Clarence",
                            Points = 6,
                            Rank = 10
                        },
                        new
                        {
                            UsernameFK = "sstephan",
                            PoolNameFK = 3,
                            Contestant = "Lindsey",
                            Points = 5,
                            Rank = 11
                        },
                        new
                        {
                            UsernameFK = "ffrancis",
                            PoolNameFK = 3,
                            Contestant = "Silas",
                            Points = 4,
                            Rank = 12
                        },
                        new
                        {
                            UsernameFK = "llucy",
                            PoolNameFK = 3,
                            Contestant = "Linda",
                            Points = 3,
                            Rank = 13
                        },
                        new
                        {
                            UsernameFK = "aadam",
                            PoolNameFK = 3,
                            Contestant = "Carl",
                            Points = 2,
                            Rank = 14
                        },
                        new
                        {
                            UsernameFK = "rrosalind",
                            PoolNameFK = 3,
                            Contestant = "Jessie",
                            Points = 1,
                            Rank = 15
                        },
                        new
                        {
                            UsernameFK = "jjayden",
                            PoolNameFK = 3,
                            Contestant = "Diane",
                            Points = 0,
                            Rank = 16
                        });
                });

            modelBuilder.Entity("DotNet.Models.UserProfile", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Username = "rrosalind",
                            Name = "Rosalind",
                            Password = "password"
                        },
                        new
                        {
                            Username = "jjeff",
                            Name = "Jeff",
                            Password = "password"
                        },
                        new
                        {
                            Username = "abutler",
                            Name = "Alex",
                            Password = "password"
                        },
                        new
                        {
                            Username = "nnina",
                            Name = "Nina",
                            Password = "password"
                        },
                        new
                        {
                            Username = "ppatrica",
                            Name = "Patrica",
                            Password = "password"
                        },
                        new
                        {
                            Username = "kkelley",
                            Name = "Kelley",
                            Password = "password"
                        },
                        new
                        {
                            Username = "jjayden",
                            Name = "Jayden",
                            Password = "password"
                        },
                        new
                        {
                            Username = "ttaylor",
                            Name = "Taylor",
                            Password = "password"
                        },
                        new
                        {
                            Username = "pparis",
                            Name = "Paris",
                            Password = "password"
                        },
                        new
                        {
                            Username = "kkathleen",
                            Name = "Kathleen",
                            Password = "password"
                        },
                        new
                        {
                            Username = "aadam",
                            Name = "Adam",
                            Password = "password"
                        },
                        new
                        {
                            Username = "sstephan",
                            Name = "Stephan",
                            Password = "password"
                        },
                        new
                        {
                            Username = "ffrancis",
                            Name = "Francis",
                            Password = "password"
                        },
                        new
                        {
                            Username = "aapril",
                            Name = "April",
                            Password = "password"
                        },
                        new
                        {
                            Username = "llucy",
                            Name = "Lucy",
                            Password = "password"
                        },
                        new
                        {
                            Username = "mmorgan",
                            Name = "Morgan",
                            Password = "password"
                        });
                });

            modelBuilder.Entity("DotNet.Models.Pool", b =>
                {
                    b.HasOne("DotNet.Models.UserProfile", "UserProfile")
                        .WithMany("Pools")
                        .HasForeignKey("HostFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("DotNet.Models.PoolMember", b =>
                {
                    b.HasOne("DotNet.Models.Pool", "Pool")
                        .WithMany("Members")
                        .HasForeignKey("PoolNameFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotNet.Models.UserProfile", "UserProfile")
                        .WithMany("Members")
                        .HasForeignKey("UsernameFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pool");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("DotNet.Models.Pool", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("DotNet.Models.UserProfile", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Pools");
                });
#pragma warning restore 612, 618
        }
    }
}
