// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNet.Migrations
{
    [DbContext(typeof(SamplePoolDBContext))]
    [Migration("20250627190425_AddBracketMemberTable")]
    partial class AddBracketMemberTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNet.Models.BracketMember", b =>
                {
                    b.Property<string>("UserFK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PoolIdFK")
                        .HasColumnType("int");

                    b.Property<int>("OrderOut")
                        .HasColumnType("int");

                    b.Property<string>("Contestant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.HasKey("UserFK", "PoolIdFK", "OrderOut");

                    b.HasIndex("PoolIdFK");

                    b.ToTable("BracketMembers");
                });

            modelBuilder.Entity("DotNet.Models.Pool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HostFK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsBracketStyle")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HostFK");

                    b.ToTable("Pools");
                });

            modelBuilder.Entity("DotNet.Models.PoolMember", b =>
                {
                    b.Property<string>("UsernameFK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PoolNameFK")
                        .HasColumnType("int");

                    b.Property<string>("Contestant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.HasKey("UsernameFK", "PoolNameFK");

                    b.HasIndex("PoolNameFK");

                    b.ToTable("PoolMembers");
                });

            modelBuilder.Entity("DotNet.Models.UserProfile", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("DotNet.Models.BracketMember", b =>
                {
                    b.HasOne("DotNet.Models.Pool", "Pool")
                        .WithMany("Brackets")
                        .HasForeignKey("PoolIdFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotNet.Models.UserProfile", "UserProfile")
                        .WithMany("Brackets")
                        .HasForeignKey("UserFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pool");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("DotNet.Models.Pool", b =>
                {
                    b.HasOne("DotNet.Models.UserProfile", "UserProfile")
                        .WithMany("Pools")
                        .HasForeignKey("HostFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("DotNet.Models.PoolMember", b =>
                {
                    b.HasOne("DotNet.Models.Pool", "Pool")
                        .WithMany("Members")
                        .HasForeignKey("PoolNameFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotNet.Models.UserProfile", "UserProfile")
                        .WithMany("Members")
                        .HasForeignKey("UsernameFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pool");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("DotNet.Models.Pool", b =>
                {
                    b.Navigation("Brackets");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("DotNet.Models.UserProfile", b =>
                {
                    b.Navigation("Brackets");

                    b.Navigation("Members");

                    b.Navigation("Pools");
                });
#pragma warning restore 612, 618
        }
    }
}
